"""Macde catalog, section, and name not unique

Revision ID: c8b020029f94
Revises: 
Create Date: 2024-07-31 23:11:11.025881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b020029f94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('courses_catalog_number_key', type_='unique')
        batch_op.drop_constraint('courses_class_section_key', type_='unique')
        batch_op.drop_constraint('courses_course_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('courses_course_name_key', ['course_name'])
        batch_op.create_unique_constraint('courses_class_section_key', ['class_section'])
        batch_op.create_unique_constraint('courses_catalog_number_key', ['catalog_number'])

    # ### end Alembic commands ###
