"""Macde catalog, section, and name not unique

Revision ID: c8b020029f94
Revises: 
Create Date: 2024-07-31 23:11:11.025881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b020029f94'
down_revision = None
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

def upgrade():
    # Check if the table exists before trying to drop it
    bind = op.get_bind()
    table_exists_query = text("""
        SELECT EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_name = :table_name
        )
    """)
    
    table_exists = bind.execute(table_exists_query, {'table_name': 'schedules'}).scalar()
    
    if table_exists:
        op.execute('DROP TABLE schedules CASCADE')





def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('courses_course_name_key', ['course_name'])
        batch_op.create_unique_constraint('courses_class_section_key', ['class_section'])
        batch_op.create_unique_constraint('courses_catalog_number_key', ['catalog_number'])

    # ### end Alembic commands ###
